update keyscan

diff --git a/.github/workflows/kamaldeploy.yml b/.github/workflows/kamaldeploy.yml
--- a/.github/workflows/kamaldeploy.yml
+++ b/.github/workflows/kamaldeploy.yml
@@ -41,7 +41,7 @@ jobs:
           echo "$SSH_PRIVATE_KEY" > ~/.ssh/homewardtails.pem
           echo "$RAILS_MASTER_KEY" > config/credentials/production.key
           chmod 600 ~/.ssh/homewardtails.pem
-          ssh-keyscan -H homewardtails.org >> ~/.ssh/known_hosts || echo "failed"
+          ssh-keyscan homewardtails.org >> ~/.ssh/known_hosts || echo "failed"
 
       - name: Kamal Deploy
         run: kamal deploy
